spring:
  # JPA 설정
  jpa:
    properties:
      hibernate:
        # 실행되는 쿼리 콘솔 출력
        show_sql: true
        # 콘솔 창에 출력되는 쿼리를 가독성 좋게 포매팅
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.MySQLDialect

  # 데이터베이스 연결 설정
  datasource:
    password: aA!123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: member123
    url: jdbc:mysql://localhost:3306/member123

  h2:
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-secret: '....'
            client-id: '....'
            scope: email, profile
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

# 토큰 제공자
jwt:
  secret_key: blog-springboot
  issuer: kky5163@naver.com